alias PD_up="docker-compose -f ~/PD/docker-compose.yml up -d"
alias PD_down="docker-compose -f ~/PD/docker-compose.yml down"
alias PD_start="docker-compose -f ~/PD/docker-compose.yml start"
alias PD_stop="docker-compose -f ~/PD/docker-compose.yml stop"
alias PD_update="docker-compose -f ~/PD/docker-compose.yml pull"
alias PD_build="docker-compose -f ~/PD/docker-compose.yml build"
