---
version: "2.1"
services:
  lidarr:
    image: ghcr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/dietpi_userdata/config:/config
      - /mnt/dietpi_userdata/music:/music
      - /mnt/dietpi_userdata/downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
