---
version: "2.1"
services:
  mylar3:
    image: ghcr.io/linuxserver/mylar3
    container_name: mylar3
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/downloader/config:/config
      - /mnt/downloader/comics:/comics
      - /mnt/downloader:/downloads
    ports:
      - 8090:8090
    restart: unless-stopped
