---
version: "2.1"
services:
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/downloader/config/radarr:/config
      - /mnt/downloader/movies:/movies
      - /mnt/downloader/downloadclient-downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
