---
version: "2.1"
services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/downloader/config/sonarr:/config
      - /mnt/downloader/tvseries:/tv
      - /mnt/downloader/downloadclient-downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
