  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - UMASK_SET=022 #optional
    volumes:
      - ./volumes/sonarr/data:/config
      - /home/pi/Pi-Downloader/media/tvshows:/tv
      - /home/pi/Pi-Downloader/media/downloads/completed/tv:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
