  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - UMASK_SET=022 #optional
    volumes:
      - /home/pi/data/appdata/sonarr/data:/config
      - /home/pi/data/media/tvshows:/tv
      - /home/pi/data/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
