  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - /home/pi/data/appdata/lidarr/config:/config
      - /home/pi/data/media/music:/music
      - /home/pi/data/downloads/completed/Music:/downloads
    ports:
      - 8686:8686
