  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - UMASK_SET=022 #optional
    volumes:
      - ./volumes/lidarr/config:/config
      - ./media/music:/music
      - ./downloads/completed/Music:/downloads
    ports:
      - 8686:8686
