---
version: "2.1"
services:
  nzbget:
    image: ghcr.io/linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/downloader/config/nzbget:/config
      - /mnt/downloader/downloads:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped
