  nzbhydra2:
    image: ghcr.io/linuxserver/nzbhydra2
    container_name: nzbhydra2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ./volumes/nzbhydra2/config:/config
      - ./media/downloads:/downloads
    ports:
      - 5076:5076
    restart: unless-stopped
