  nzbget:
    image: dtroncy/rpi-nzbget
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ./volumes/nzbget/config:/config
      - ./downloads:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped
