  nzbget:
    image: ghcr.io/linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /home/pi/data/appdata/nzbget/config:/config
      - /home/pi/data/downloads:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped
