  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Los_Angeles
      - UMASK_SET=022 #optional
    volumes:
      - ./volumes/radarr/config:/config
      - ./media/movies:/movies
      - ./downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
