  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Los_Angeles
      - UMASK_SET=022 #optional
    volumes:
      - /home/pi/data/appdata/radarr/config:/config
      - /home/pi/data/media/movies:/movies
      - /home/pi/data/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
